name: itinera
description: A Flutter travel planning UI application using Material 3.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.3.2
  supabase_flutter: ^2.12.0
  http: ^1.6.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/stitch_itinera/
    - assets/images/
    - assets/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
